# Generated by Django 5.1.7 on 2025-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='total_assets',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='total_equity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='total_liabilities',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
