# Generated by Django 5.1.7 on 2025-06-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_dividend_yield_stock_market_stock_market_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
