# Generated by Django 5.1.7 on 2025-05-31 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('stocks', '0002_stock_dividend_yield_stock_market_stock_market_cap_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('current_value', models.FloatField()),
                ('change', models.FloatField()),
                ('change_percent', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('trade_value', models.BigIntegerField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('above', '이상'), ('below', '이하')], max_length=10)),
                ('target_price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stocks.stock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma5', models.FloatField(blank=True, null=True)),
                ('ma20', models.FloatField(blank=True, null=True)),
                ('ma60', models.FloatField(blank=True, null=True)),
                ('rsi', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('macd_histogram', models.FloatField(blank=True, null=True)),
                ('bollinger_upper', models.FloatField(blank=True, null=True)),
                ('bollinger_middle', models.FloatField(blank=True, null=True)),
                ('bollinger_lower', models.FloatField(blank=True, null=True)),
                ('stochastic_k', models.FloatField(blank=True, null=True)),
                ('stochastic_d', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technical', to='stocks.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stocks', models.ManyToManyField(blank=True, related_name='watchlists', to='stocks.stock')),
            ],
        ),
    ]
