# Generated by Django 5.2.1 on 2025-06-09 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_marketindex_alert_technicalindicator_watchlist'),
        ('stocks', '0003_stock_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_type', models.CharField(choices=[('spectral', 'Spectral Clustering'), ('agglomerative', 'Agglomerative Clustering')], max_length=20)),
                ('cluster_id', models.IntegerField()),
                ('cluster_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('dominant_sectors', models.JSONField(default=list)),
                ('stock_count', models.IntegerField(default=0)),
                ('avg_market_cap', models.BigIntegerField(blank=True, null=True)),
                ('avg_per', models.FloatField(blank=True, null=True)),
                ('avg_pbr', models.FloatField(blank=True, null=True)),
                ('characteristics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('cluster_type', 'cluster_id')},
            },
        ),
        migrations.CreateModel(
            name='AgglomerativeCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('cluster_label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agglomerative_cluster', to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['cluster_id'], name='analysis_ag_cluster_2dea3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpectralCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField()),
                ('cluster_label', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spectral_cluster', to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['cluster_id'], name='analysis_sp_cluster_7bf518_idx')],
            },
        ),
    ]
