# Generated by Django 5.2.1 on 2025-06-11 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_clusteranalysis_agglomerativecluster_spectralcluster'),
        ('stocks', '0003_stock_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_type', models.CharField(choices=[('spectral', 'Spectral Clustering'), ('agglomerative', 'Agglomerative Clustering')], max_length=20)),
                ('cluster_id', models.IntegerField()),
                ('neighbor_rank', models.IntegerField()),
                ('distance', models.FloatField()),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_sources', to='stocks.stock')),
                ('target_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_targets', to='stocks.stock')),
            ],
            options={
                'ordering': ['cluster_type', 'cluster_id', 'source_stock', 'neighbor_rank'],
                'indexes': [models.Index(fields=['cluster_type', 'cluster_id'], name='analysis_st_cluster_61e12f_idx'), models.Index(fields=['cluster_type', 'source_stock'], name='analysis_st_cluster_0313b7_idx'), models.Index(fields=['distance'], name='analysis_st_distanc_6254e7_idx'), models.Index(fields=['neighbor_rank'], name='analysis_st_neighbo_e1ca68_idx')],
                'unique_together': {('cluster_type', 'source_stock', 'target_stock')},
            },
        ),
    ]
