# Generated by Django 5.1.7 on 2025-05-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField()),
                ('positive', models.DecimalField(decimal_places=2, max_digits=4)),
                ('negative', models.DecimalField(decimal_places=2, max_digits=4)),
                ('top_keywords', models.TextField()),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='stocks.stock')),
            ],
        ),
    ]
